### ISSUE TITLE
Coding team tasks for Week of 9/7

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#220]
Here are the coding team tasks for the Week of 8/31.

- [x] Read the GRNmap and GRNsight papers handed out at the meeting; look at GRNmap publications page for slides and posters about GRNmap.
- [x] Declare on issue #204 when you are going to work each week (ideally overlapping 4-hour block)
- [x] Everyone meet with @trixr4kdz to do a code walkthrough
- [x] @jtorre39 and @yshin4 will familiarize selves with MATLAB
- [x] take a look at issue #51 (initialize arrays) as what we will approach first, using TDD.  
- [x] declare more issues with granular tasks needed to tackle #51

**Comment by kdahlquist** [comment]
- [ ] I'm going to add one more task that I forgot to mention at the meeting.  Please read the code of conduct that we are considering adding to our project.  Issue #219.  See: http://contributor-covenant.org/

**Comment by trixr4kdz** [comment]
@jtorre39, @cazinge, @trixr4kdz, and @yshin4 have read/are reading the GRNmap/GRNsight papers.

**Comment by trixr4kdz** [comment]
I've met with @yshin4 and @jtorre39 for the code walkthrough.

**Comment by kdahlquist** [comment]
Here is the updated list for the week of 9/7:
- [ ] some still need to review the code of conduct #219 
- [ ] review of differential equations (an online resource)
- [ ]  @jtorre39 will familiarize self with MATLAB
- [ ] take a look at issue #51 (initialize arrays) as what we will approach first, using TDD.
- [ ] declare more issues with granular tasks needed to tackle #51

**Comment by kdahlquist** [comment]
these are done.
