### ISSUE TITLE
Data Analysis team tasks for week of 9/12

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#226]
From now on, we'll create an issue at the weekly meeting to keep track of tasks assigned for the upcoming week.  I'm writing this now in advance of the Monday meeting on 9/12.

- [x] Everyone, remember to read and agree to the Code of Conduct Issue #219; post a comment there when you are done.
* @bklein7 and @Nwilli31 are working on the following:
    - [x] implementing an R script to automatically generate random networks #223 
    - [x] working through an R tutorial (this is an ongoing issue to work on in the background) #225 
* I'm going to assign @Nwilli31 to:
    - [ ] go back to looking at mRNA degradation rates #7 
* @khorstmann and @maggie-oneil are working on the following:
    - [ ] investigating the literature to find graph properties that will help us analyze the model data #224 
    - [ ] start looking into using MATLAB to compute some of the graph properties that are relevant #224 
* All four data analysis team members will: 
    - [x] work on the TRACE documentation for GRNmap #170

**Comment by kdahlquist** [comment]
Remember to read and agree to the Code of Conduct Issue #219; post a comment there when you are done.

**Comment by kdahlquist** [comment]
All incomplete tasks have been migrated to a new issue for the week of 9/19 issue #235.
