### ISSUE TITLE
Coding Team tasks for week of 9/14

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#233]
- [ ] #231 Preallocate GRNstruct Arrays to Zeros Arrays 
- [ ] #232 Checker to validate expression worksheets 
- [ ] #158 GRNmap must be able to deal with with missing values
- [x] everyone come to @kdahlquist's seminar on Friday at 3:00 in LSB auditorium
- [x] everyone come to the GRNsight party on Friday at 4:00 on the LSB 2nd floor terrace
- [x] everyone go through and click on the links to download all of the source code and executables on the [Download](http://kdahlquist.github.io/GRNmap/downloads.html) page to see if the download counter responds; do it live logged in to GoogleAnalytics.
- [ ] Monday, September 26 at 3:00 in LSB 118, @NAnguiano is going to give a journal club presentation on [Jacomy, M., Venturini, T., Heymann, S., & Bastian, M. (2014). ForceAtlas2, a continuous graph layout algorithm for handy network visualization designed for the Gephi software. PloS one, 9(6), e98679.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679).  Please come if you can.

**Comment by jtorre39** [comment]
Buttons seem to be working in real time.

**Comment by jtorre39** [comment]
The array preallocation for average and standard deviation happen in read input sheet so if we want to separate the preallocation of the arrays for average and standard deviation then we would need to relocate the mean and standard deviations into another routine.

**Comment by trixr4kdz** [comment]
We have started creating the function for preallocating the arrays. @jtorre39 has initiated a pull request, which contains the changes that we made.

**Comment by kdahlquist** [comment]
Open issues have been moved to the Task list for 9/21 #238.
