### ISSUE TITLE
Data Analysis Team Tasks for Week of 9/19

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#235]
The tasks for this week:

* @bklein7 and @Nwilli31 are working on the following:
    - [x] working through an R tutorial (ongoing) #225 
    - [x] @Nwilli31 will finish up a new spreadsheet with mRNA degradation rates #7 
    - [x] @bklein7 will implement an R script to automatically generate degree distribution charts from an input adjacency matrix. #230 
* @khorstmann and @maggie-oneil are working on the following:
    - [ ] investigating the literature to find graph properties that will help us analyze the model data #224.  the bibliography should be finished up soon (look into <biblio> tag on OWW or Zotaro.
    - [ ] start looking into using MATLAB to compute some of the graph properties that are relevant #224.  We'll start with betweenness centrality.
* Everyone is working on TRACE documentation #170 
    - [ ] @khorstmann and @maggie-oneil will take first four
    - [ ] @bklein7 and @Nwilli31 will take second four.

Don't forget that we will have @NAnguiano's journal club at 3:00  next Monday in LSB 118 #228.

**Comment by khorstmann** [comment]
Accomplishments this week: (more detail can be found in September 20th entry of: http://www.openwetware.org/wiki/Kristen_M._Horstmann_Lab_Notebook#September_20.2C_2016)
- Explored the bioinformatics Matlab toolbox on the Dahlquist lab computers. Played around with some of the functions and searched for betweenness centrality/anything else we may want. 
- Functions of note: "graphallshortestpaths" with and without weights and with or without direction. Also has "graphshortestpath" which determines the single source shortest path from node S to all other nodess in the graph. Has four different options of algorithms to figure out how to find the shortest path. 
Then checked through the Systems Biology and evolution article. Mian functions include betweenness centrality, clustering coefficient, closeness centrality, etc. Also creates random networks of nodes, even up to as large as 80,000 nodes. 
Only issue is that the users manual posted on github seems to require a Texas A&M login to view, but still may be worth exploring downloading.

**Comment by kdahlquist** [comment]
moved incomplete tasks to new issue #246.
