### ISSUE TITLE
Coding Team tasks for week of 9/21

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#238]
- [x] Monday, September 26 at 3:00 in LSB 118, @NAnguiano is going to give a journal club presentation on [Jacomy, M., Venturini, T., Heymann, S., & Bastian, M. (2014). ForceAtlas2, a continuous graph layout algorithm for handy network visualization designed for the Gephi software. PloS one, 9(6), e98679.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679).  Please come if you can.
- [ ] @bengfitzpatrick will update his computer lab computers with MATLAB 2014b #237.
- [x] Issues #232 and #158 are on somewhat of a hold this week while the team reviews the "big picture" with regards to the data structure and architecture of GRNmap.
    - [x] @cazinge and @jtorre39 will generate an input sheet and run GRNmap as a user to familiarize themselves with where the input data are coming from.
    - [x] #231 can proceed to the extent that the arrays listed on the wiki need to be matched up to the input data to see whether they are storing "raw" data from the input sheet, "derived" data computed from something from the input sheet, or they aren't actually referring to anything any more.
- [ ] @cazinge will create issue about streamlining website during/after conversion to Jekyll #212.

@dondi and @kdahlquist advise that while it is useful to take this bird's eye view, we are still constrained by the format of the input sheet and by the way the program works.  We want to favor "good enough" or "better" as opposed to the "perfect" solution.

**Comment by trixr4kdz** [comment]
I've revised the wiki to specify which arrays are read directly from Excel, which are manipulated, etc. Another thorough look at the code shows that there are already initializations for the arrays. I would try to move these preallocations but that would require separating certain operations into new scripts.

**Comment by kdahlquist** [comment]
Remaining tasks moved over to next week #244.
