### ISSUE TITLE
Coding Team tasks for Week of 9/28

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#244]
- [x] Don't forget, the GRNmap coding team meeting will take place in @dondi's office in Doolan on Wednesday, October 5. #243.
- [x] @bengfitzpatrick still working on getting the correct version of MATLAB installed on the computers i his lab.
- [x] @jtorre39 should fix the input workbooks that he reported in issue #241.
- [x] @jtorre39 and @trixr4kdz are working on remaining issues from #231 and #242.
- [x] after that @jtorre39 and @trixr4kdz will move on to #158.  Work on the checker #232 as needed for #158 for now.

**Comment by dondi** [comment]
Peter Allison is coming to @bengfitzpatrick’s lab at 2pm today October 5 to accomplish the second checkbox.

**Comment by dondi** [comment]
@cazinge is finished with the conversion to Jekyll, just needs to be merged (https://github.com/kdahlquist/GRNmap/pull/234), then will prioritize programming work over additional documentation. Follow-up tasks to the merge, such as documentation to the wiki, page/download count, picture on the people page, and streamlining the wiki, etc. will be captured as separate tasks. Listing the remaining issues becomes the next immediate task.

**Comment by dondi** [comment]
@trixr4kdz will complete #231 definitively by annotating @bengfitzpatrick list of properties with links to the specific lines/versions of code that initialize them. This will make them easier to verify.

**Comment by dondi** [comment]
Last few tasks have been checked off to acknowledge the work. Follow-up issue will summarize the listing/linking part for verification.

**Comment by kdahlquist** [comment]
Are we waiting to close this?  I would rather move the remaining tasks to the next week so we don't have competing task lists.

**Comment by dondi** [comment]
The MATLAB install was supposed to happen this afternoon plus the Jekyll merge just needed one merge conflict resolution pass so I was looking to close this right after @bengfitzpatrick and @cazinge check those off, respectively. Seemed to be close enough that we could just wait then close. I'll see where we are at end of day.

**Comment by bengfitzpatrick** [comment]
Peter came by after I'd left.  He emailed that the task is complete.  I will check first thing tomorrow and close if done.
