### ISSUE TITLE
Data Analysis Team tasks for week of 10/3

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#246]
The tasks for this week:

* @kdahlquist has "review requested" for 
    - [ ] #7 (mRNA deg rates)
    - [ ] #230 (degree distribution charts)
    - [ ] possibly #224 (bibliography for graph properties)
* @bklein7 and @Nwilli31 are working on the following:
    - [ ] #245, generating and vetting input workbooks
* @khorstmann and @maggie-oneil are working on the following:
    - [x] start looking into using MATLAB to compute some of the graph properties that are relevant #224.  We'll start with betweenness centrality.  @maggie-oneil and @khorstmann should try to get the SBET toolbox up and running.  @khorstmann will e-mail corresponding and first author (separately) asking for access to documentation, cc'ing @kdahlquist on the message
* Everyone is working on TRACE documentation #170 
    - [ ] @khorstmann and @maggie-oneil will take first four
    - [ ] @bklein7 and @Nwilli31 will take second four.

**Comment by kdahlquist** [comment]
relevant tasks moved to #251.
