### ISSUE TITLE
Coding Team tasks for Week of 10/5

### ISSUE THREAD

**Issue by dondi** [kdahlquist/GRNmap#249]
- [x] October 12 meeting is in LSB 118. @dondi will be traveling so will not make it.
- [x] @cazinge is going to work on finalizing the conversion of the website to Jekyll #212.
- [x] @trixr4kdz will wrap up #231 by cataloguing and linking initializations directly to the code, for verification by @bengfitzpatrick and @dondi.
- [ ] @jtorre39 will wrap up #242 by cataloguing and linking globals directly to the code, for verification by @bengfitzpatrick and @dondi.
- [ ] @cazinge, after finishing #212 (by merging #234) and documenting follow-up tasks to this, will start with #158 in earnest.

**Comment by dondi** [comment]
*Clarification:* The respective issues will be marked as `review requested` when the above work is done, after which the PIs can verify then close.

@cazinge It looks like #219 will also be covered by the Jekyll site conversion, so mark that as `review requested` as well when the PR is merged.

**Comment by kdahlquist** [comment]
Thanks for the detailed comments.

I booked the LSB 118 conference room for the October 12 meeting so we can use the large monitors for group review of code and issues.

**Comment by trixr4kdz** [comment]
I finished linking the initialization for each of the arrays in the GRNstruct. See issue #231

**Comment by jtorre39** [comment]
I have accomplished the cataloging of globals within GRNmap. It can be observed at issue #242.

**Comment by kdahlquist** [comment]
remaining tasks have been moved over to #257
