### ISSUE TITLE
Data Analysis Team Tasks for Week of 10/10

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#251]
The tasks for this week:

* @kdahlquist has "review requested" for 
    - [x] #7 (mRNA deg rates)
    - [ ] #230 (degree distribution charts)
    - [x] #224 (bibliography for graph properties)
    - [ ] #245, generating and vetting input workbooks
* @bklein7 and @Nwilli31 are working on the following:
    - [x] #245, generating and vetting input workbooks, swap when ready
    - [ ] #241, update 16_tests workbooks on beta branch to be consistent with our formatting guidelines 
    - [ ] if time, do the degree-distribution charts for the "real" networks (store in PowerPoint)
    - [ ] if time, generated some (like 10) random networks for each of the "real" ones and store them in a workbook by themselves, and make the degree distribution charts for them (don't do dZAP1 until it has been vetted).
* @khorstmann and @maggie-oneil are working on the following:
    - [ ] #224.  @maggie-oneil and @khorstmann will work on getting the SBET toolbox up and running, starting with betweenness centrality.
* Everyone is working on TRACE documentation #170 
    - [ ] @khorstmann and @maggie-oneil will take first four
    - [ ] @bklein7 and @Nwilli31 will take second four.

**Comment by khorstmann** [comment]
For reference, the SBE Toolbox "User's Manual" was sent to me from the first author, Dr. Kranti Konganti and can be found here: https://promis.tamu.edu/projects/sbetoolbox/wiki/SBEToolbox_User_Manual

**Comment by kdahlquist** [comment]
all unfinished tasks have been moved over to #260.
