### ISSUE TITLE
Coding team task list for week of 10/12

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#257]
- [ ] @trixr4kdz will wrap up #231 by running the code on 3 test files (see issue) and sending them to @bengfitzpatrick for review.
- [ ] @trixr4kdz will then work with @jtorre39 will work on #242 by pulling out the globals.  See comments on issue.
- [ ] @cazinge, will start with #158 and catalog all places in the code where missing data arrays need work.
- [x] meeting location for 10/19 will be in @dondi's office in Doolan.

**Comment by dondi** [comment]
@cazinge got sick on Tuesday and is recovering.

**Comment by dondi** [comment]
@jtorre39 did not encounter any issues with pulling out globals, but just has not finished pulling out all of them. This task will continue on to this week.

**Comment by dondi** [comment]
@trixr4kdz would have been done but for the issue regarding the `adjacency_mat` global (described in greater detail in #231). Resolving it is her task for this week.
