### ISSUE TITLE
Data Analysis Team Tasks for Week of 10/17

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#260]
The tasks for this week:

* @kdahlquist has "review requested" for 
    - [ ] #230 (degree distribution charts)
    - [ ] #245, generating and vetting input workbooks (after requested changes are made)
* @bklein7 and @Nwilli31 are working on the following:
    - [ ] #245, generating and vetting input workbooks, finishing off requested changes
    - [ ] #241, update 16_tests workbooks on beta branch to be consistent with our formatting guidelines 
    - [ ] start some model runs (details to come)
* @khorstmann and @maggie-oneil are working on the following:
    - [ ] #259  @maggie-oneil and @khorstmann will work on getting the SBET toolbox up and running, starting with betweenness centrality.
* Everyone is working on TRACE documentation #170 
    - [ ] @khorstmann and @maggie-oneil will take first four
    - [ ] @bklein7 and @Nwilli31 will take second four.

**Comment by maggie-oneil** [comment]
Worked with @khorstmann on figuring out how to run the SBET toolbox. It has been installed and formatted on both computers in the LSB 263 Lab. To run in MATLAB, input command SBEGUI. Betweenness centrality, etc. is fairly intuitive. See Kristen's comment for more detailed notes due to more familiarity with operating MATLAB.

**Comment by khorstmann** [comment]
At beginning of installation, asked for which organism we were using and S. cerevisiae was listed and selected. This is useful as the nodes can be looked up in the S. cerevisiae database and given details on what each gene does specifically. 
Statistical tests can be done at a push of the button, but must be noted as it goes, as the output dialog doesn't have a scrolling memory (only gives the most recent output). Detailed notes can be found in this weeks journal: 
http://www.openwetware.org/wiki/Kristen_M._Horstmann_Lab_Notebook#Notes_on_SBEToolbox

I emailed Dr. Konganti from Texas AM to try to get more details on the exact formatting of the input sheets. In the user manual provided, there were no details as to where the regulators/regulatees went (columns, rows etc). If he doesn't respond, will continue to play around with small networks to try to determine the overall layout.

**Comment by Nwilli31** [comment]
Because my computer shut down unexpectedly, my most recent Bookmarks were erased. I did not find too many supplemental files, but I am still going back to find the papers with mRNA decay rates and supplementary data sets.

**Comment by khorstmann** [comment]
Ok Dr. Konganti emailed me back and was pretty vague in his layout instructions.... Basically said the same instructions that were in the user manual and then gave a short example with "You can upload a simple tab delimited text file with at least 2 columns. Each row represents links between 2 data points a.k.a nodes." So didn't really give any new, groundbreaking info.

**Comment by kdahlquist** [comment]
That's OK.  It might be better to use a two column format because it is generally accepted that the source node is on the left and the target node is on the right.  Try doing it that way with some simple networks.  Then, for the more complex "real" ones, we can use GRNsight to convert the adjacency matrix to a two column SIF format.  Just upload the excel file and then export to SIF.  If you can give me a specific link to the portion of the documentation to read, I might be able to decipher something as well.

**Comment by khorstmann** [comment]
Ok, Maggie and I can try that out tomorrow. 

Here's the specific link from the user manual for the Reading and Writing of Data. https://promis.tamu.edu/projects/sbetoolbox/wiki/SBEToolbox_User_Manual#Reading-Writing-Data 

In the email, he copied and pasted the first 3 lines then went on to give the small example, so wasn't anything much more specific

**Comment by kdahlquist** [comment]
Relevant tasks have been moved to #266.
