### ISSUE TITLE
Coding team task list for week of 10/19 and 10/26

### ISSUE THREAD

**Issue by dondi** [kdahlquist/GRNmap#263]
- [x] @trixr4kdz will wrap up #231 by tracking down the `adjacency_mat` leftover global bug on the final merged version, making sure to run tests (manual or not) then sending the code to @bengfitzpatrick for review.
- [ ] @jtorre39 will continue to pull out the remaining globals for #242.
- [ ] @cazinge, will continue with #158 and catalog all places in the code where missing data arrays need work.
- [x] @bengfitzpatrick will provide OneCard access to UHall 2752 for @jtorre39 and @cazinge.
- [x] meeting location for 10/26 will be back in the LSB 118 conference room.

**Comment by jtorre39** [comment]
Still working on the issue of #242 . So far we're working on tests for localizing the readInputSheet, populateGlobals function, and the globalsToLocals function. While working with some of the current test files I had to refactor some of the variables which ended up being quite time consuming. As soon as we finish the tests implementing the changes for readInputSheet and for the other two functions we should be able to finish localizing readInputSheet, the populateGlobals function, and the globalsToLocals function.

**Comment by trixr4kdz** [comment]
The adjacency_mat bug has been fixed since we've created the populateGlobals function (see the current beta change [here]()). However, I have not had time to go over fixing the bug that arises with running the 21-gene network then the 4-gene network. The files that you requested for last week's meeting can be seen [here](https://github.com/trixr4kdz/GRNmap/tree/beta/test_files/review_requested/101216). As I mentioned in the comment from last week, the optimization diagnostics sheet from master is vastly different from the current beta since the calculation from before was incorrect (i.e., we were accumulating the MSEs for subsequent genes instead of calculating them for each expression profile separately). I've included the output file from a previous version where this calculation has been fixed so you can check if the current output differs.

**Comment by bengfitzpatrick** [comment]
@jtorre39 and @cazinge need to visit one-card office to complete access to UH 2752.

**Comment by jtorre39** [comment]
@trixr4kdz and I were finishing the issue #242 but broke several tests while refactoring readinputsheet to remove its globals. Issue is almost done besides debugging and further refactoring.

**Comment by dondi** [comment]
@jtorre39 will follow up based on suggestions noted in #242

**Comment by dondi** [comment]
@trixr4kdz has finished #231 and will await #242 prior to merging (and testing the merge).

**Comment by dondi** [comment]
Tasks for next week have been recorded in #270
