### ISSUE TITLE
Coding team tasks for Week of 11/2 and 11/7

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#270]
- [x] @trixr4kdz and @jtorre39 : #242 taking care of Strain and log2FC
- [x] @trixr4kdz and @jtorre39 need to merge their threads (#231 is closed, and #242 is close). put it in the right branch :)
- [ ] @cazinge, will continue with #158; he will push his work in progress for the next meeting and be sure to post a comment on the issue so we can know his progress.

**Comment by trixr4kdz** [comment]
I have created a pull request that needs to be checked by @jtorre39, which is the fix for the failing tests. While working on the global variable clean-up, we realized that it is a bit tricky to completely isolate the globals log2FC and Strain from the routines at the current state of the code base, which is why we are leaving them untouched for now.

**Comment by trixr4kdz** [comment]
The global variables Strain and log2FC have now been expunged from readInputSheet, output, and graphs routines. I've also renamed the field ```.Strain``` in the GRNstruct into ```.strain``` to keep up with the other variable names that we have in our code. Note that this minor change does not affect the names used in the workbooks.

**Comment by cazinge** [comment]
I've added the tests for #158, I was initially going to commit this result after my doctors appointment but it's been an hour and I still haven't been processed, so I had time to kill. I separated the tests into multiple areas of concern so each of the pain points for working with this new structure can be properly addressed. I'll discuss each of those in #158 right now.

**Comment by kdahlquist** [comment]
remaining issue has been moved to #286.
