### ISSUE TITLE
Data Analysis Team tasks for Week of 11/28

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#292]
The tasks for this week:
- @kdahlquist has "review requested" for 
  - [ ] #230 (degree distribution charts)
  - [ ] #245, generating and vetting input workbooks
- @khorstmann and @maggie-oneil:
  - [ ] #290 compute graph statistics with Gephi
- @bklein7 and @Nwilli31
  - [ ] #274 needs a couple more edits based on last week's meeting (write discussion)
  - [ ] #275 add within strain ANOVA data (need rest of strains) (write discussion)
  - [ ] #241 needs to generate new output workbooks
- everyone
  - [ ] wrap-up for the semester #291

**Comment by khorstmann** [comment]
Gathered the stats for unweighted and weighted for CIN5, GLN3, HAP4, ZAP1, and Wild Type
[GephiOutputsFall16.pptx](https://github.com/kdahlquist/GRNmap/files/620723/GephiOutputsFall16.pptx)
Saved all outputs (weighted on paradoxus, unweighted on boulardii 2) as Excel sheets.

**Comment by maggie-oneil** [comment]
Researched the equations and definitions for the statistics models that Gephi uses in it's outputs.
[Statistics Models Used in Gephi.pptx](https://github.com/kdahlquist/GRNmap/files/620732/Statistics.Models.Used.in.Gephi.pptx)
Saved weighted output tables on paradoxus

**Comment by bklein7** [comment]
For #241, I generated the 16 new output sheets. There was a minor discrepancy in these outputs, run using the beta version of GRNmap, so I have held off on uploading the new files.

For #274, I made all requested changes and uploaded the a new version of the bar chart analysis [PowerPoint Presentation](https://github.com/kdahlquist/DahlquistLab/blob/master/documents/Five-Networks_Bar-Chart-Analysis_BK20161116.pptx). Moving forward, I can add the new CIN5 model run data to the charts. I did not see the output sheets for these runs uploaded to the Dahlquist Lab repository yet though and am also wondering if both network size results should be included.

More details on my work from this week can be found in comments on #241 and #274.

**Comment by maggie-oneil** [comment]
Looked into the outputs we were getting for the strongly connected component statistic, and basically the number widely varies because it's looking at the maximum number of vertices that are needed to have directed connections between two vertices. The sources I looked at describe it as being the "maximal set of vertices C ⊆ V such that for every pair of vertices _u_ and _v_, there is a directed path from _u_ to _v_ and a directed path from _v_ to _u_."(source - [https://goo.gl/Cvnv5K](url))

Also looked more into the algorithm Gephi is using to calculate this statistic, and it's called Tarjan's strongly connected component algorithm. Here's the paper written by Tarjan on his algorithm - [https://goo.gl/9SsU4V](url), and here's a link to the code Gephi uses, which can be found on GitHub [https://goo.gl/lzWSLp](url)

**Comment by kdahlquist** [comment]
@maggie-oneil, the links in your last comment are broken, can you fix them?  You can edit a previously made comment by clicking on the pencil icon.  Thanks.

**Comment by kdahlquist** [comment]
Open tasks moved to Issue #303.
