### ISSUE TITLE
Coding team tasks for week of 1/18

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#302]
- [x] continue swarm on #158 
 - [x] read PLoS article about github and check off name when done #299 
 - [x] is issue #203 closable now?

Just a reminder to us at the meeting to post comments on the relevant issue, not this task list.

**Comment by cazinge** [comment]
Finished 4 hours for last week today because of first week of school stuffs, Mainly catching up and reunderstanding where we were at in the matrix dissection; on my fork is just the work that I've been doing  that hasn't been synced with Trixie and Justin's. Coming to meeting shortly

**Comment by trixr4kdz** [comment]
At this week's coding session, we've:
- refactored convertToNestedStructure to be more readable and fixed the bug we were having with the cells being indexed incorrectly,
- Stubbed out and implemented most of the tests discussed in this week's meeting,
- Read the GitHub article from issue #299 
- Started converting existing tests to accommodate our new nested matrix data structure
Also, @cazinge has independently looked into #221 and has decided that the effort that would be put into setting up a CI service is not worth it, as the current solutions to this problem don't work very nicely with Matlab.

Going forward, we need to:
- Implement the permutation tests and error throwing on recieving a complete row of NaNs,
- Begin converting the codebase to utilize our new data structure,
- Start converting the current tests to assert the structure of our new data structure.

**Comment by dondi** [comment]
For the second bullet, the heart of the code is in the least squares error function. The loops in that code should be adjusted to now acknowledge the new data structure with possible missing cells.

**Comment by dondi** [comment]
When the first bullet concludes, we can close #158 and open new tasks for the second and third bullets.

**Comment by dondi** [comment]
With the Undergraduate Research Symposium abstracts due on February 10, #301 is now priority 0 and is part of the deliverable for next week. Draft the abstract on the wiki.

**Comment by trixr4kdz** [comment]
The permutation plus warning/error tests have all been added and are passing. I've created the new issues as #310 and #311 for the bullet points on converting the codebase and converting current tests, respectively.

A draft for the symposium abstract is commented on #301.

**Comment by kdahlquist** [comment]
new tasks moved over to issue #314
