### ISSUE TITLE
Data Analysis Team Tasks for Week of 1/19

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#303]
The tasks for this week:
- @kdahlquist has "review requested" for 
  - [ ] #230 (degree distribution charts)
- @khorstmann and @maggie-oneil:
  - [ ] #290 compute graph statistics with Gephi
- @bklein7 and @Nwilli31
  - [ ] #274 needs a couple more edits based on last week's meeting (write discussion)
  - [ ] #275 add within strain ANOVA data (need rest of strains) (write discussion)
  - [ ] #241 needs to generate new output workbooks
- everyone
  - [ ] prepare poster for the SoCal Systems Biology Conference

**Comment by maggie-oneil** [comment]
Presentation for today 
[MO_UPDATED1.19.16Statistics.Models.Used.in.Gephi.pptx](https://github.com/kdahlquist/GRNmap/files/718097/MO_UPDATED1.19.16Statistics.Models.Used.in.Gephi.pptx)

**Comment by kdahlquist** [comment]
[MO_UPDATED1.19.16Statistics.Models.Used.in.Gephi.pptx](https://github.com/kdahlquist/GRNmap/files/718183/MO_UPDATED1.19.16Statistics.Models.Used.in.Gephi.pptx)

**Comment by khorstmann** [comment]
https://github.com/kdahlquist/GRNmap/blob/master/documents/posters/KH_MO_GRNmap_UCI_draft.pptx here's the finished draft of Maggie's and my poster. We'll be making any last minute changes tomorrow that are sent to us.

**Comment by kdahlquist** [comment]
Got the poster.  If the changes are minor, I'll go ahead and do them myself.  I'll keep you posted.

**Comment by maggie-oneil** [comment]
[Distance-Matrix_From-Unweighted-Adjacency-15-genes_28-edges_GJ-dHAP4-fam_strains-added_Sigmoid_Estimation.xlsx](https://github.com/kdahlquist/GRNmap/files/749307/Distance-Matrix_From-Unweighted-Adjacency-15-genes_28-edges_GJ-dHAP4-fam_strains-added_Sigmoid_Estimation.xlsx)

Here's the distance matrix. Might need to be looked at again to confirm correct values

**Comment by kdahlquist** [comment]
New tasks listed in #317, so closing this one.
