### ISSUE TITLE
Data analysis team tasks for week of 2/2

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#317]
Everyone (top priorities):
- [x] #301: draft abstracts on wiki (OWW or this one), post a link to it in the issue #310 for final review and submission next week.
- [x] #299: read the 10 simple rules article and check off your name when finished
- [ ] #315: brainstorm and add to list of metrics on how to analyze our data for discussion and setting priorities next week

@bklein7 and @Nwilli31:
- [x] #316: decide on which computer will be "master" computer for running models and make sure to run all the six networks on that computer.

@maggie-oneil and @khorstmann 
- [ ] #290, when @bklein7 and @Nwilli31 have generated the new versions of the random network input workbooks, run them in Gephi to gather the graph stats for them.

@kdahlquist
- [ ] review requested for #230

**Comment by kdahlquist** [comment]
All open tasks have been moved over to #324.
