### ISSUE TITLE
Data analysis team tasks for week of 2/16, 2/23, and 3/2

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#324]
Individual issues/tasks for the upcoming week as discussed in Thursday's meeting.

After the break, at our next meeting we will review the talks and posters for the LMU Symposium, so please have drafts ready. #301.

@bklein7:
- [x] #230 meet with @kdahlquist to resolve (priority 0)
- [x] #315: analysis of weights (priority 0)
- [ ] #330: multiple regression (priority 0)

@maggie-oneil:
- [ ] #290, since has finished running the db-derived networks, start compiling the data and computing some descriptive stats (priority 0)
- [ ] #328, compute weighted degrees in Excel (priority 0)
- [ ] #331, distance matrix for db5 (priority 0.5)

@khorstmann:
- [ ] #325, compute graph stats for random unweighted networks from @Nwilli31.  Goal is 30, but don't have to finish them all before compiling data and doing descriptive stats as described in issue. (priority 0)
- [ ] #329, compute weighted degrees in Excel (priority 0.5)

@Nwilli31: 
- [x] #326, analyze MSE data for database-derived and random networks (priority 0)
- [x] #327, finish generating the 30 random network input sheets and run through GRNmap in background (priority 0.5)

@kdahlquist
- [x] in order to complete review requested for #230, need to meet with @bklein7 to debug (priority 0)
- [ ] #332 create gex (priority 0.5)

@bengfitzpatrick 
- [x] help @Nwilli31 with #326 to compute minMSE's

**Comment by khorstmann** [comment]
Here is a powerpoint of tables for the Gephi outputs I generated for each network 
[Gephi Outputs for all networks.pptx](https://github.com/kdahlquist/GRNmap/files/781844/Gephi.Outputs.for.all.networks.pptx)

**Comment by maggie-oneil** [comment]
Ignore previous comment - didn't realize Kristen was logged in instead of me.

Here's my initial powerpoint of Gephi outputs for all networks 
[Gephi Outputs for all networks.pptx](https://github.com/kdahlquist/GRNmap/files/781849/Gephi.Outputs.for.all.networks.pptx)

**Comment by kdahlquist** [comment]
[network_alphabetical_layout_key.pdf](https://github.com/kdahlquist/GRNmap/files/782015/network_alphabetical_layout_key.pdf)

This is the GRNsight layout template for the current crop of networks we are analyzing.  I'll find a place in the DahlquistLab repository for it later, but I'm putting it here for now.

**Comment by kdahlquist** [comment]
As discussed in the meeting today, we are going to rename our networks as follows:
db1: wt-derived network
db2: dCIN5-derived 14-gene network
db3: dCIN5-derived 17-gene network
db4: dGLN3-derived network
db5: dHAP4-derived network
db6: dZAP1-derived network

This is to remind ourselves that these networks don't really have much to do with the strain except that that strain's ANOVA data was fed into YEASTRACT.

Also, we need to also remember that we artificially put CIN5, GLN3, HAP4, HMO1, SWI4, and ZAP1 into these networks, so we shouldn't read too much into the fact that there are many common edges because roughly a third of the genes in the network, we put in there.

The random networks we are working with this semester are based on db5 and are called rand1, rand2, etc. up to rand30.

**Comment by kdahlquist** [comment]
I have updated the task list with the new issues for each team member.  Take a look at the top comment.

This is a reminder that if you have an update for your task, please make the comment on the appropriate issue and not here so that we keep the comment threads with the issues and don't lose them when we close the weekly task list.

**Comment by kdahlquist** [comment]
Noting that @bengfitzpatrick needs to help @Nwilli31 with #326.

**Comment by khorstmann** [comment]
Compiled the centrality stats (betweenness, harmonic, closeness, and eccentricity) together into excel file with multiple sheets in GRNmap repository-> data-> 15 genes to make analysis of it easier.

Also noticed two of the random networks were the same (Networks 4 & 5) so added random network 11 to the mix to have 10 unique random networks

**Comment by khorstmann** [comment]
Rough draft of slides can be found here: https://github.com/kdahlquist/GRNmap/blob/master/documents/presentations/HorstmannURS_Draft2.pptx

**Comment by kdahlquist** [comment]
Reminder for everyone that now that the symposium is over, to go back to this task list and work on your individual issues/tasks.

**Comment by kdahlquist** [comment]
All open tasks have been moved over to #343, so closing this one.
